baseURL = "https://in.ota.tensevntysevn.cf/"
title = "Geographic OTA Services"
contentDir = "metadata/content"

[outputs]
    section = ["rss"]
    page = ["rss"]

[params]
	mirrorCode = "liquidtelecom"